// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_similarartists_artist_ from "./routes/api/similarartists/[artist].ts";
import * as $index from "./routes/index.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $Table from "./islands/Table.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/similarartists/[artist].ts": $api_similarartists_artist_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Form.tsx": $Form,
    "./islands/Main.tsx": $Main,
    "./islands/Table.tsx": $Table,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
